apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
            - name: grafana-provisioning
              mountPath: /etc/grafana/provisioning
            - name: grafana-config
              mountPath: /etc/grafana/config.ini
              subPath: config.ini
            - name: grafana-dashboards
              mountPath: /var/lib/grafana/dashboards
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: antonio
          ports:
            - containerPort: 3000
      volumes:
        - name: grafana-data
          emptyDir: {}
        - name: grafana-provisioning
          hostPath:
            path: ./config/grafana/provisioning
        - name: grafana-config
          hostPath:
            path: ./config/grafana/config.ini
        - name: grafana-dashboards
          hostPath:
            path: ./config/grafana/dashboards
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
